# Generated by Django 4.2.1 on 2023-05-27 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_comment',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tasks.status'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
