# Generated by Django 4.2.1 on 2023-05-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_created_at_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.cards'),
        ),
    ]
