# Generated by Django 4.2.1 on 2023-05-28 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cards',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cards'),
        ),
    ]
