# Generated by Django 4.2.1 on 2023-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_cards_created_at_cards_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
